### ISSUE TITLE
How can I run this code in order to reproduce your amazing results?

### ISSUE THREAD

**Issue by MohammadVahidiPro** [hmllmh/RSTC#3]
Hi, I'm very interested in your research and I would love to reproduce your results if you could provide me the hyperparameters and commands needed to run the code and achieve your amazing results, I would be immensely grateful.

**Comment by MohammadVahidiPro** [comment]
up plz

**Comment by hmllmh** [comment]
Hello, we have 1. added all the hyperparameters in run_code.sh and 2. added all the augmented datasets we generated using contextual augment (we use the code in https://github.com/amazon-science/sccl ).
sorry to reply late because I am busy these days.

**Comment by hmllmh** [comment]
收到
